version: '3.4'
services:
  credebl-biometric-service:
    image: ${IMAGE_NAME}
    container_name: credebl-biometric-service
    ports:
      - "3002:3001"
    env_file:
      - .env
    restart: unless-stopped
