name: Docker Compose Deploy BIO

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build Docker image
        run: docker build -t bio .
        
      - name: Save Docker image
        run: docker save bio:latest > bio.tar
        
      - name: Transfer Docker image
        uses: appleboy/scp-action@v0.1.4
        with:
          host:  ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "bio.tar"
          target: "/home/ubuntu/workspace/biometric-service/cicd/bio"

      - name: SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd /home/ubuntu/workspace/biometric-service/cicd/bio
            sudo docker stop bio || true
            sudo docker rm -f bio || true
            sudo docker load -i bio.tar
            sudo docker run --name bio -dp 3001:3001 --env-file .env bio
