name: QA Tag Workflow

on:
  push:
    tags:
      - 'qa*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/qa-')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          docker -v
          cat /etc/os-release
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region ap-southeast-1

      - name: Get runner IP address
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Print Runner IP Address
        id: print-ip
        run: |
         echo "Runner IP Address: ${{ steps.ip.outputs.ipv4 }}"
         
      - name: Whitelist runner IP address
        run: |
         aws ec2 authorize-security-group-ingress \
         --group-id ${{ secrets.DEV_INSTANCE_SG_ID }} \
         --protocol tcp \
         --port 22 \
         --cidr ${{ steps.ip.outputs.ipv4 }}/32 

      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 589943763826.dkr.ecr.ap-southeast-1.amazonaws.com
          
      
      - name: Build and tag Docker image
        run: |
          docker build -t qabiometricservice .
          docker tag qabiometricservice:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/qabiometricservice:biolatest
          echo 'docker images'
          docker images
          
       
      - name: Push Docker image to AWS ECR
        run: 
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/qabiometricservice:biolatest

      - name: SSH into EC2 instance and pull Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.QA_EC2_INSTANCE_IP }}
          username: ${{ secrets.QA_SSH_USERNAME }}
          key: ${{ secrets.QA_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.EC2_INSTANCE_PASSPHRASE }}
          script: |
            docker login -u AWS -p "$(aws ecr get-login-password --region ap-southeast-1)" ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com
            docker stop biolatest || true
            docker rm -f biolatest || true
            docker rmi ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/qabiometricservice:biolatest
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/qabiometricservice:biolatest
            cd /home/${{ secrets.DEV_SSH_USERNAME }}/workspace/biometric-service           
            docker run -d -p 3001:3001 --name biolatest --env-file .env ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/qabiometricservice:biolatest
            
      -  name: Revoke runner IP address
         run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.DEV_INSTANCE_SG_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

    
