name: QA Tag Workflow

on:
  push:
    tags:
      - 'qa*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    

    steps:
      - name: Check if tag creator is allowed
        id: check-user
        run: |
          ALLOWED_USERS=("Chimi1999" "dev-dungana")
          echo "Tag pushed by: ${{ github.actor }}"
          is_allowed="false"
          for user in "${ALLOWED_USERS[@]}"; do
            if [[ "${{ github.actor }}" == "$user" ]]; then
              is_allowed="true"
              break
            fi
          done
          echo "is_allowed=$is_allowed" >> $GITHUB_OUTPUT

      - name: Delete tag if unauthorized
        if: steps.check-user.outputs.is_allowed != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Unauthorized tag push detected by ${{ github.actor }}. Deleting tag: $TAG_NAME"
          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/tags/$TAG_NAME
          exit 1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region ap-southeast-1
          
      - name: Get runner IP address
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Print Runner IP Address
        id: print-ip
        run: |
         echo "Runner IP Address: ${{ steps.ip.outputs.ipv4 }}"
         
      - name: Whitelist runner IP address
        run: |
         aws ec2 authorize-security-group-ingress \
         --group-id ${{ secrets.DEV_INSTANCE_SG_ID }} \
         --protocol tcp \
         --port 22 \
         --cidr ${{ steps.ip.outputs.ipv4 }}/32 
         
      - name: Copy Docker Compose file to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.QA_EC2_INSTANCE_IP }}
          username: ${{ secrets.QA_SSH_USERNAME }}
          key: ${{ secrets.QA_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.EC2_INSTANCE_PASSPHRASE }}
          source: docker-compose.yml
          target: /home/${{ secrets.QA_SSH_USERNAME }}/workspace/biometric-service/

      
      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com

      
      - name: Build and tag Docker image
        run: |
          yarn
          docker build -t qabiometricservice .
          docker tag qabiometricservice:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/qabiometricservice:biolatest
          
       
      - name: Push Docker image to AWS ECR
        run: 
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/qabiometricservice:biolatest

      - name: SSH into EC2 instance and pull Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.QA_EC2_INSTANCE_IP }}
          username: ${{ secrets.QA_SSH_USERNAME }}
          key: ${{ secrets.QA_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.EC2_INSTANCE_PASSPHRASE }}
          script: |
            docker login -u AWS -p "$(aws ecr get-login-password --region ap-southeast-1)" ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com
            cd /home/ubuntu/workspace/biometric-service
            docker-compose pull biometric-service
            docker-compose up -d biometric-service
            sudo docker images -f "dangling=true" -q | xargs -r sudo docker rmi || echo 'No dangling images to remove'

      -  name: Revoke runner IP address
         run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.DEV_INSTANCE_SG_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
