name: Stage Tag Workflow

on:
  push:
    tags:
      - 'stage*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region ap-southeast-1
          
      - name: Get runner IP address
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Print Runner IP Address
        id: print-ip
        run: |
         echo "Runner IP Address: ${{ steps.ip.outputs.ipv4 }}"
         
      - name: Whitelist runner IP address
        run: |
         aws ec2 authorize-security-group-ingress \
         --group-id ${{ secrets.DEV_INSTANCE_SG_ID }} \
         --protocol tcp \
         --port 22 \
         --cidr ${{ steps.ip.outputs.ipv4 }}/32 
         
      - name: Copy Docker Compose file to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.STAGE_EC2_INSTANCE_IP }}
          username: ${{ secrets.STAGE_SSH_USERNAME }}
          key: ${{ secrets.STAGE_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.EC2_INSTANCE_PASSPHRASE }}
          source: credebl-docker-compose.yml
          target: /home/${{ secrets.STAGE_SSH_USERNAME }}/workspace/credebl-biometric-service/

      
      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com

      
      - name: Build and tag Docker image
        run: |
          docker build -t stagebiometricservice .
          docker tag stagebiometricservice:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/stagebiometricservice:credeblbiolatest
          
       
      - name: Push Docker image to AWS ECR
        run: 
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/stagebiometricservice:credeblbiolatest

      - name: SSH into EC2 instance and pull Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGE_EC2_INSTANCE_IP }}
          username: ${{ secrets.STAGE_SSH_USERNAME }}
          key: ${{ secrets.STAGE_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.EC2_INSTANCE_PASSPHRASE }}
          script: |
            docker login -u AWS -p "$(aws ecr get-login-password --region ap-southeast-1)" ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com
            cd /home/${{ secrets.STAGE_SSH_USERNAME }}/workspace/credebl-biometric-service
            docker-compose -f ./credebl-docker-compose.yml pull credebl-biometric-service
            docker-compose -f ./credebl-docker-compose.yml up -d credebl-biometric-service
            

      -  name: Revoke runner IP address
         run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.DEV_INSTANCE_SG_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32